<<<<<<< HEAD
version: '3.4'

services:
  board.api:
    image: ${DOCKER_REGISTRY-}boardapi
    container_name: board.api
    build:
      context: .
      dockerfile: src/Services/BoardService/Board.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081" 

  board.database:
    image: postgres:latest
    container_name: board.database
    environment:
      - POSTGRES_DB=boards_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=11012004
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
=======
version: '3.7'

networks:
  dev:
    driver: bridge

services:
  identity.api:
    container_name: identity.api
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    depends_on:
      - "mongodb"
      - "redis"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - dev
    links:
      - "redis" 

  mongodb:
    container_name: identity.db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data
    networks:
      - dev

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - dev

volumes:
  mongodb-data:
  redis-data:
>>>>>>> 6c964979b6171ec9718ddb6747a2ae89c28641df
