version: '3.9'

networks:
  dev:
    driver: bridge

services:
  app:
    depends_on:
      - "mongodb"
      - "redis"
    container_name: identity-service
    ports:
      - "8088:80" 
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev
  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - dev
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  mongodb-data:
  redis-data:
