version: '3.7'

networks:
  dev:
    driver: bridge

services:
  board.api:
    image: ${DOCKER_REGISTRY-}boardapi
    build:
      context: .
      dockerfile: Board.API\Dockerfile
    depends_on:
      - "app_db"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - dev

  app_db:
    container_name: app_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11012004
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres_data:
